### ISSUE TITLE
Image is not displayed correctly

### ISSUE THREAD

**Issue by derflippo** [NicholasRasi/MMM-OnlineImagesViewer#1]
Hello, I have the following config in use:

{
	module: "MMM-OnlineImagesViewer",
	position: "bottom_right",
	config: {
		images: [
			"https://www.meteolivevco.it/webcam/Gravellona-sud.jpg",
			"http://192.168.178.59/tmpfs/auto.jpg?usr=admin&pwd=admin",
			"http://192.168.178.47/tmpfs/auto.jpg?usr=admin&pwd=admin",
			"http://192.168.178.102/tmpfs/auto.jpg?usr=admin&pwd=admin"
		],
		random: false,
		updateInterval: 60 * 1 * 1000, // every 1 min
		showAll: false,
		maxWidth: "300px",
		numColumns: 2
	}
}

As you can see, I have added four webcam pictures.
The first one is a public one, which works perfectly.
The last three webcams are private and run in the home network, but are unfortunately not displayed correctly. 
Like here:
<img width="399" alt="Bildschirmfoto 2024-02-23 um 13 12 58" src="https://github.com/NicholasRasi/MMM-OnlineImagesViewer/assets/62194826/584b23a3-b9c6-417c-8f42-1c25658adfa1">

When I open the links of the private webcams in the browser, the images are displayed as intended. No authentication is necessary as the credentials are already included in the http link.
Unfortunately, I suspect that the plugin cannot handle the credentials.

I have also tried opening the links on the Raspberry's built-in Chrome browser. This works perfectly. Unfortunately, I don't know which browser engine the module uses...

I cannot disable authentication on the cameras. So this is not an option.

I hope someone has an idea and can help me, as I have been looking for a working solution to display my webcams on the MagicMirror for years.

**Comment by NicholasRasi** [comment]
Hi @derflippo,
you should check why your image is not loaded.

So, from your Raspberry:
- start MagicMirror as server: `npm run server`.
- open the browser and go to [http://localhost:8080/](http://localhost:8080/).
- open the Developers Tools and check the network tab. You should see the request, and why it is not successful.

Please post here the request, so we can check it.

**Comment by derflippo** [comment]
Thanks for the hint @NicholasRasi,
I just checked the network tab and it displays following:

`Error: username or password error,please input again.`

The error message is clear, that's okay.
However, I don't know how to otherwise bypass the authentication.
Is there another way to fill the URL with credentials that Chromium/MagicMirror can open?

**Comment by NicholasRasi** [comment]
I think the problem was because the plugin adds a parameter to the end of the URL to update the image. But your URLs already have some parameters, so the resulting url was not correct.

I should fix this in #2, @derflippo could you update the plugin and check it?

**Comment by derflippo** [comment]
Your update seems to have solved the problem @NicholasRasi!
Only the first of my three cameras is still not displayed with the same error. I will troubleshoot this myself again...

Thank you for your great help!
